ActionBarTimerMessage: "You are in combat for %time%"
ActionBarEnemyMessage: "There are players nearby! Get %deactivationDistance% blocks away from them to get out of combat"
GeneralTimerDuration: 20 #in seconds
CombatTimerDuration: 60 #in seconds
MinimumDeactivationDistancePvP: 50 #Distance to an Enemy in Blocks

DeathCrateType: "BARREL"

BanTimeOnLeave: 180 #in seconds

BlockModificationWhileInCombat: false #False means that block modification is disabled during combat

HologramMainTextColor: "RED"
HologramSecondTextColor: "YELLOW"
#Make sure the Hologram Colors are two of the following: DARK_RED, RED, GOLD, YELLOW, DARK_GREEN, GREEN, AQUA,
#DARK_AQUA, DARK_BLUE, BLUE, LIGHT_PURPLE, DARK_PURPLE, WHITE, GRAY, DARK_GRAY, BLACK
HologramMainText: "%player%'s Grave"
HologramSecondText: "They disconnected during Combat"
