GeneralTimerDuration: 20

CombatTimerDuration: 60
MinimumDeactivationDistancePvP: 50
  #Distance to an Enemy

DeathCrateType: "BARREL"

HologramMainTextColor: "RED"
HologramSecondTextColor: "YELLOW"
  #Make sure the Hologram Colors are two of the following: DARK_RED, RED, GOLD, YELLOW, DARK_GREEN, GREEN, AQUA,
  #DARK_AQUA, DARK_BLUE, BLUE, LIGHT_PURPLE, DARK_PURPLE, WHITE, GRAY, DARK_GRAY, BLACK
HologramMainText: "'s Grave"
HologramSecondText: "They disconnected during Combat"