ActionBarMessage: "You are in combat for %time%"
GeneralTimerDuration: 20
CombatTimerDuration: 60
MinimumDeactivationDistancePvP: 50
  #Distance to an Enemy

BanTimeOnLeave: 180 #in seconds

DeathCrateType: BARREL